services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432"

  backend:
    build: .
    restart: always
    depends_on:
      - migrate
    volumes:
      - /var/www/krasintegra/upload:/app/upload
    env_file:
      - .env
    ports:
      - "8012:8012"

  migrate:
    build: .
    command: alembic upgrade head
    env_file: .env
    depends_on:
      - db

  init-root:
    build: .
    command: python -m src.testovoe.main.create_root_user
    env_file: .env
    depends_on:
      - migrate

volumes:
  db_data:
