"""Add created_by field to user

Revision ID: 3ff5f64daef7
Revises: 43414ef5e0b0
Create Date: 2025-09-12 18:30:15.996789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff5f64daef7'
down_revision: Union[str, None] = '43414ef5e0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_foreign_key(None, 'user', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password')
    op.drop_column('user', 'created_by_id')
    # ### end Alembic commands ###
