"""Add ON DELETE CASCADE to token_user relatin

Revision ID: afe215d50d79
Revises: 3ff5f64daef7
Create Date: 2025-09-16 13:29:16.630235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe215d50d79'
down_revision: Union[str, None] = '3ff5f64daef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('token_user_id_fkey'), 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key(op.f('token_user_id_fkey'), 'token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
